server:
  port: 8085
  
spring:
  application:
    name: crawler-management
    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


booking:
   prebooking:
      awit:
         time-in-seconds: 300    