server:
  port: 8084
  
spring:
  application:
    name: payment-management
    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


booking:
   prebooking:
      awit:
         time-in-minutes: 5    