server:
  port: 8082
  
spring:
  application:
    name: booking-management
    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


booking:
   prebooking:
      awit:
         time-in-minutes: 5    