USE `FUN_TIME`;


delimiter $$

CREATE TRIGGER BOOKING_AUDIT_ENTRY AFTER UPDATE ON BOOKING
  FOR EACH ROW BEGIN
	INSERT INTO BOOKING_AUDIT
		(
		BOOKING_AUDIT_TS,
		BOOKING_ID,
		NO_OF_SEATS,
		TIME_OF_BOOKING,
		BOOKING_STATUS,
		TIME_OF_BOOKING_CONFIRMATION,
		ACTUAL_PRICE,
		DISCOUNT,
		DISCOUNTED_PRICE,
		TIME_OF_BOOKING_CANCEL,
		BOOKING_USER_ID,
		BOOKING_MOVIE_SHOW_TIME_ID)
	VALUES
		(now(),
		old.BOOKING_ID,
		old.NO_OF_SEATS,
		old.TIME_OF_BOOKING,
		old.BOOKING_STATUS,
		old.TIME_OF_BOOKING_CONFIRMATION,
		old.ACTUAL_PRICE,
		old.DISCOUNT,
		old.DISCOUNTED_PRICE,
		old.TIME_OF_BOOKING_CANCEL,
		old.BOOKING_USER_ID,
		old.BOOKING_MOVIE_SHOW_TIME_ID);
  END;
$$

delimiter $$