USE `FUN_TIME`;

/* Find movies in city */

/*
SELECT movie_id, MOVIE_TITLE, MOVIE_DESCRIPTION, DURATION, LANG, GENERE, COUNTRY 
 FROM CITY C, CINEMA_HALL CH, SCREEN S, MOVIE_SHOW_TIME MST, MOVIE M
WHERE 
C.CITY_SHORT_NAME = 'KOLK' AND C.CITY_ID =  CH.CINEMA_HALL_CITY_ID
AND CH.CINEMA_HALL_ID = S.SCREEN_CINEMA_HALL_ID
AND MST.MOVIE_SHOW_TIME_SCREEN_ID = S.SCREEN_ID
AND M.MOVIE_ID = MST.MOVIE_SHOW_TIME_MOVIE_ID */

/* Find halls with city and movie */
/*SELECT CINEMA_HALL_ID, CINEMA_HALL_SHORT_NAME, CINEMA_HALL_NAME, MOVIE_SHOW_TIME_STARTTIME, SCREEN_NAME
 FROM CITY C, CINEMA_HALL CH, SCREEN S, MOVIE_SHOW_TIME MST, MOVIE M
WHERE 
C.CITY_SHORT_NAME = 'KOLK' AND C.CITY_ID =  CH.CINEMA_HALL_CITY_ID
AND CH.CINEMA_HALL_ID = S.SCREEN_CINEMA_HALL_ID
AND MST.MOVIE_SHOW_TIME_SCREEN_ID = S.SCREEN_ID
AND M.MOVIE_ID = MST.MOVIE_SHOW_TIME_MOVIE_ID AND M.MOVIE_ID=1 */

/* Find halls with city and movie with tickets */
/*SELECT CINEMA_HALL_ID, CINEMA_HALL_SHORT_NAME, CINEMA_HALL_NAME, MOVIE_SHOW_TIME_STARTTIME,A.SCREEN_ID,A.MOVIE_SHOW_TIME_ID FROM 
(SELECT  CINEMA_HALL_ID, CINEMA_HALL_SHORT_NAME, CINEMA_HALL_NAME, MOVIE_SHOW_TIME_STARTTIME,SCREEN_ID,MOVIE_SHOW_TIME_ID
FROM CITY C, CINEMA_HALL CH, SCREEN S, MOVIE_SHOW_TIME MST, MOVIE M 
WHERE 
C.CITY_SHORT_NAME = 'KOLK' AND C.CITY_ID =  CH.CINEMA_HALL_CITY_ID
AND CH.CINEMA_HALL_ID = S.SCREEN_CINEMA_HALL_ID
AND MST.MOVIE_SHOW_TIME_SCREEN_ID = S.SCREEN_ID
AND M.MOVIE_ID = MST.MOVIE_SHOW_TIME_MOVIE_ID AND M.MOVIE_ID=1) A, SCREEN_SEAT SS, BOOKING  B, SHOW_SEAT SE
#OUTER JOIN
WHERE 
SS.SCREEN_CINEMA_HALL_SEAT_ID=A.SCREEN_ID AND SS.SCREEN_SEAT_ID=SE.SCREEN_SEAT_ID
AND B.BOOKING_ID=SE.BOOKING_ID AND B.BOOKING_MOVIE_SHOW_TIME_ID = A.MOVIE_SHOW_TIME_ID
GROUP BY A.MOVIE_SHOW_TIME_ID, A.SCREEN_ID #HAVING COUNT(SEAT_TYPE) */

#FIND ALL SEAT IN A SCREEN
/*SELECT SCREEN_SEAT_ID, SEAT_NUMBER, SEAT_TYPE
FROM CITY C, CINEMA_HALL CH, SCREEN S, MOVIE_SHOW_TIME MST, MOVIE M, SCREEN_SEAT SS
WHERE 
C.CITY_SHORT_NAME = 'KOLK' AND C.CITY_ID =  CH.CINEMA_HALL_CITY_ID
AND CH.CINEMA_HALL_ID = S.SCREEN_CINEMA_HALL_ID
AND MST.MOVIE_SHOW_TIME_SCREEN_ID = S.SCREEN_ID
AND M.MOVIE_ID = MST.MOVIE_SHOW_TIME_MOVIE_ID AND M.MOVIE_ID=1
AND SS.SCREEN_CINEMA_HALL_SEAT_ID = S.SCREEN_ID
AND S.SCREEN_ID=1 AND MST.MOVIE_SHOW_TIME_ID= 1
AND CH.CINEMA_HALL_ID=1 */

