USE `FUN_TIME`;

/* Find movies in city */

/*
SELECT movie_id, MOVIE_TITLE, MOVIE_DESCRIPTION, DURATION, LANG, GENERE, COUNTRY 
 FROM CITY C, CINEMA_HALL CH, SCREEN S, MOVIE_SHOW_TIME MST, MOVIE M
WHERE 
C.CITY_SHORT_NAME = 'KOLK' AND C.CITY_ID =  CH.CINEMA_HALL_CITY_ID
AND CH.CINEMA_HALL_ID = S.SCREEN_CINEMA_HALL_ID
AND MST.MOVIE_SHOW_TIME_SCREEN_ID = S.SCREEN_ID
AND M.MOVIE_ID = MST.MOVIE_SHOW_TIME_MOVIE_ID */

/* Find halls with city and movie */
SELECT CINEMA_HALL_ID, CINEMA_HALL_SHORT_NAME, CINEMA_HALL_NAME, MOVIE_SHOW_TIME_STARTTIME, SCREEN_NAME
 FROM CITY C, CINEMA_HALL CH, SCREEN S, MOVIE_SHOW_TIME MST, MOVIE M
WHERE 
C.CITY_SHORT_NAME = 'KOLK' AND C.CITY_ID =  CH.CINEMA_HALL_CITY_ID
AND CH.CINEMA_HALL_ID = S.SCREEN_CINEMA_HALL_ID
AND MST.MOVIE_SHOW_TIME_SCREEN_ID = S.SCREEN_ID
AND M.MOVIE_ID = MST.MOVIE_SHOW_TIME_MOVIE_ID AND M.MOVIE_ID=1
